PROCESSING_PHRASES = (
    'Twirling Monocle',
    'Fluffing Cravat',
    'Sipping Earl Grey with Pinky Extended',
    'Tapping Cane Rhythmically',
    'Adjusting Suspenders with a Flick',
    'Dusting Lapel with a Silk Brush',
    'Folding Pocket Square Precisely',
    'Polishing Cufflinks with a Velvet Cloth',
    'Checking Waistcoat Buttons',
    'Stroking Silk Top Hat',
    'Twirling Mustache with Wax',
    'Unfurling a Pocket Square',
    'Measuring Cufflinks with Calipers',
    'Adjusting Glove Seams',
    'Inspecting Lorgnette for Smudges',
    'Dabbing Colognes with a Q-Tip',
    'Calibrating a Pocket Compass',
    'Straightening a Spats Buckle',
    'Polishing a Brass Knuckle Duster',
    'Counting Monogram Stitches',
    'Tuning a Pocket Watch',
    'Folding a Handkerchief into a Swan',
    'Adjusting a Top Hat Band',
    'Polishing Spectacles with a Monogrammed Cloth',
    'Twirling a Walking Stick',
    'Sipping Brandy from a Crystal Glass',
    'Examining a Fob Chain with a Magnifier',
    'Adjusting a Bow Tie with a Miniature Ruler',
    'Dusting a Tailcoat with a Feathers Duster',
    'Measuring Cuff Length with Calipers',
    'Polishing a Silver Cigarette Case',
    'Fluffing a Silk Scarf',
    'Checking Time on a Skeleton Watch',
    'Adjusting a Cravat Pin',
    'Polishing a Patent Leather Shoe',
    'Twirling a Foil Epee',
    'Scenting a Letter with Lavender',
    'Adjusting a Pince-Nez',
    'Folding a Newspaper with Precision',
    'Measuring Cufflink Diameter with Calipers',
    'Polishing a Silver Flask',
    'Adjusting a Spats Strap',
    'Dabbing Wrist with Colognes',
    'Tuning a Pocket Watch with a Tiny Screwdriver',
    'Straightening a Diamond Stickpin',
    'Polishing a Silver Cane Tip',
    'Fluffing a Silk Handkerchief',
    'Counting Threads in a Linen Handkerchief',
    'Adjusting a Watch Chain',
    'Polishing a Monogrammed Cufflink',
    'Sipping Tea through a Mustache Guard',
    'Twirling a Pocket Watch Chain',
    'Folding a Letter into a Crane',
    'Adjusting a Top Hat with a Feathers Duster',
    'Polishing a Silver Cigarette Holder',
    'Measuring the Perfect Cravat Angle',
    'Dusting a Lapel with a Diamond-Encrusted Brush',
    'Calibrating a Scent Diffuser',
    'Tuning a Pocket Watch with a Loupe',
    'Adjusting a Diamond-Encrusted Cufflink',
    'Polishing a Gold-Plated Pocket Knife',
    'Folding a Silk Scarf into an Origami Swan',
    'Sipping Sherry from a Crystal Decanter',
    'Measuring Glove Fit with Calipers',
    'Adjusting a Monocle Chain',
    'Polishing a Silver-Plated Snuff Box',
    'Twirling a Silk Handkerchief',
    'Dabbing a Lapel with Scented Water',
    'Folding a Pocket Square into a Rose',
    'Adjusting a Top Hat with a Diamond-Studded Brush',
    'Polishing a Platinum Cufflink',
    'Counting the Stitches in a Monogram',
    'Sipping Absinthe through a Sugar Cube',
    'Measuring a Cravat with a Tailor’s Tape',
    'Polishing a Gold-Encrusted Pocket Watch',
    'Adjusting a Silk-Top Hat Band',
    'Fluffing a Velvet Cufflink',
    'Tuning a Pocket Watch with a Microscope',
    'Dusting a Tailcoat with a Diamond-Tipped Brush',
    'Folding a Handkerchief into a Butterfly',
    'Adjusting a Diamond-Studded Cravat Pin',
    'Polishing a Platinum-Plated Cane',
    'Sipping Champagne from a Crystal Flute',
    'Measuring Cufflink Depth with Laser Calipers',
    'Adjusting a Monocle with a Diamond-Encrusted Wrench',
    'Polishing a Ruby-Encrusted Pocket Square',
    'Folding a Newspaper into a Miniature Eiffel Tower',
    'Counting the Dots on a Silk Tie',
    'Sipping Brandy from a Gold-Plated Snifter',
    'Tuning a Pocket Watch with a Sonic Screwdriver',
    'Adjusting a Top Hat with a Feather-Trimmed Brush',
    'Polishing a Diamond-Encrusted Shoe Horn',
    'Folding a Handkerchief into a Peacock',
    'Measuring Glove Seam Tension with a Tensiometer',
    'Dabbing a Cufflink with Scented Oil',
    'Adjusting a Silk-Top Hat with a Monogrammed Brush',
    'Polishing a Gold-Plated Cufflink',
    'Fluffing a Linen Handkerchief with a Feather',
    'Counting the Threads in a Silk Cravat',
    'Sipping Whiskey from a Crystal Tumbler',
    'Tuning a Pocket Watch with a Quantum Calibrator',
    'Adjusting a Diamond-Encrusted Spats Strap',
    'Polishing a Platinum-Plated Monocle',
    'Folding a Pocket Square into a Falcon',
    'Measuring Cufflink Symmetry with a Laser Level',
    'Dusting a Tailcoat with a Diamond-Encrusted Duster',
    'Adjusting a Top Hat with a Silk-Trimmed Brush',
    'Polishing a Gold-Plated Cane Tip',
    'Fluffing a Silk Scarf with a Feather Duster',
    'Counting the Stitches in a Monogram with a Magnifier',
    'Sipping Gin from a Crystal Goblet',
    'Tuning a Pocket Watch with a Holographic Interface',
    'Adjusting a Diamond-Studded Cufflink with Tweezers',
    'Polishing a Platinum-Plated Cigarette Case',
    'Folding a Handkerchief into a Swan (Again)',
    'Measuring Glove Fit with Nanometer Precision',
    'Dabbing a Lapel with Rare Orchid Essence',
    'Adjusting a Monocle Chain with a Micro-Adjuster',
    'Polishing a Ruby-Encrusted Cane',
    'Sipping Rum from a Silver Goblet',
    'Folding a Newspaper into a Perfect Cube',
    'Counting the Weave Patterns in a Linen Handkerchief',
    'Tuning a Pocket Watch with a Chroniton Emitter',
    'Adjusting a Top Hat with a Diamond-Encrusted Feather',
    'Polishing a Gold-Plated Pocket Knife with a Microfiber Cloth',
    'Fluffing a Silk Handkerchief with a Diamond-Tipped Brush',
    'Measuring Cravat Symmetry with a Digital Protractor',
    'Dusting a Tailcoat with a Quantum Duster',
    'Adjusting a Diamond-Studded Cravat Pin with Laser Guidance',
    'Polishing a Platinum-Encrusted Monocle with Nano-Solution',
    'Folding a Pocket Square into a Phoenix',
    'Sipping Port from a Crystal Decanter',
    'Measuring Cufflink Depth with a Subatomic Ruler',
    'Dabbing a Cufflink with Scented Nanoparticles',
    'Adjusting a Top Hat Band with a Holographic Level',
    'Polishing a Diamond-Encrusted Snuff Box with Liquid Diamond',
    'Fluffing a Velvet Cufflink with a Micro-Airbrush',
    'Counting the Stitches in a Monogram with a DNA Scanner',
    'Sipping Absinthe through a Diamond-Encrusted Sugar Cube',
    'Tuning a Pocket Watch with a Temporal Calibrator',
    'Adjusting a Silk-Top Hat with a Monogrammed Nanobrush',
    'Polishing a Gold-Plated Cane with Liquid Platinum',
    'Folding a Handkerchief into a Quantum Butterfly',
    'Measuring Glove Seam Tension with a Graviton Sensor',
    'Dusting a Tailcoat with a Photon-Enhanced Brush',
    'Adjusting a Diamond-Studded Spats Strap with a Neural Interface',
    'Polishing a Platinum-Plated Monocle with Antimatter Polish',
    'Folding a Pocket Square into a Fractal Rose',
    'Sipping Ambrosia from a Celestial Chalice',
    'Measuring Cufflink Symmetry with a Tachyon Ruler',
    'Dabbing a Cufflink with Scented Dark Matter',
    'Adjusting a Top Hat with a Singularity-Encrusted Brush',
    'Polishing a Gold-Plated Cigarette Case with Neutronium',
    'Fluffing a Silk Scarf with a Warp-Field Feathers Duster',
    'Counting the Threads in a Silk Cravat with a Quantum Microscope',
    'Sipping Starlight from a Nebula Goblet',
    'Tuning a Pocket Watch with a Reality-Adjustment Dial',
    'Adjusting a Diamond-Encrusted Cufflink with Chroniton Tweezers',
    'Polishing a Platinum-Plated Cane Tip with Exotic Matter',
    'Folding a Handkerchief into a Tesseract Swan',
    'Measuring Glove Fit with a Multidimensional Caliper',
    'Dabbing a Lapel with Essence of Distant Galaxies',
    'Adjusting a Monocle Chain with a Temporal Micro-Adjuster',
    'Polishing a Ruby-Encrusted Pocket Square with Nebula Dust',
    'Folding a Newspaper into a Klein Bottle',
    'Counting the Stitches in a Monogram with a Singularity Scanner',
    'Sipping Eternity from a Timeless Vessel',
    'Tuning a Pocket Watch with a Multiverse Calibration Tool',
    'Adjusting a Top Hat with a Reality-Warping Feather',
    'Polishing a Diamond-Encrusted Cane with Void Energy',
    'Fluffing a Linen Handkerchief with Quantum Fluff',
)