PROCESSING_PHRASES = (
    'Adjusting Glove Seams',
    'Adjusting Suspenders with a Flick',
    'Adjusting a Bow Tie with a Miniature Ruler',
    'Adjusting a Cravat Pin',
    'Adjusting a Cravat with a Warp-Field Measuring Tape',
    'Adjusting a Diamond-Encrusted Cufflink with Chroniton Tweezers',
    'Adjusting a Diamond-Encrusted Cufflink',
    'Adjusting a Diamond-Encrusted Spats Strap with Temporal Tweezers',
    'Adjusting a Diamond-Encrusted Spats Strap',
    'Adjusting a Diamond-Studded Cravat Pin with Laser Guidance',
    'Adjusting a Diamond-Studded Cravat Pin',
    'Adjusting a Diamond-Studded Cravat with Nanobot Tweezers',
    'Adjusting a Diamond-Studded Cufflink with Tweezers',
    'Adjusting a Diamond-Studded Spats Strap with a Neural Interface',
    'Adjusting a Monocle Chain with Quantum-Tuned Tweezers',
    'Adjusting a Monocle Chain with a Chroniton Micro-Adjuster',
    'Adjusting a Monocle Chain with a Micro-Adjuster',
    'Adjusting a Monocle Chain with a Temporal Micro-Adjuster',
    'Adjusting a Monocle Chain',
    'Adjusting a Monocle with a Diamond-Encrusted Wrench',
    'Adjusting a Pince-Nez',
    'Adjusting a Silk-Top Hat Band',
    'Adjusting a Silk-Top Hat with a Graviton Brush',
    'Adjusting a Silk-Top Hat with a Monogrammed Brush',
    'Adjusting a Silk-Top Hat with a Monogrammed Nanobrush',
    'Adjusting a Silted Waistcoat with a Laser-Guided Tailor\'s Chalk',
    'Adjusting a Spats Buckle with Graviton Tweezers',
    'Adjusting a Spats Buckle with Neural-Link Precision',
    'Adjusting a Spats Strap',
    'Adjusting a Top Hat Band with a Holographic Level',
    'Adjusting a Top Hat Band with a Singularity Wrench',
    'Adjusting a Top Hat Band',
    'Adjusting a Top Hat with a Diamond-Encrusted Feather',
    'Adjusting a Top Hat with a Diamond-Studded Brush',
    'Adjusting a Top Hat with a Feather-Trimmed Brush',
    'Adjusting a Top Hat with a Feathers Duster',
    'Adjusting a Top Hat with a Quantum Feather Duster',
    'Adjusting a Top Hat with a Reality-Warping Feather',
    'Adjusting a Top Hat with a Silk-Trimmed Brush',
    'Adjusting a Top Hat with a Singularity-Encrusted Brush',
    'Adjusting a Watch Chain',
    'Calibrating a Monocle with a Quantum Focus Ring',
    'Calibrating a Pocket Compass',
    'Calibrating a Scent Diffuser with Exotic Matter',
    'Calibrating a Scent Diffuser with Temporal Harmonics',
    'Calibrating a Scent Diffuser with a Tachyon Spanner',
    'Calibrating a Scent Diffuser',
    'Checking Time on a Skeleton Watch',
    'Checking Waistcoat Buttons',
    'Counting Monogram Stitches with a Multiverse Scanner',
    'Counting Monogram Stitches with a Quantum Microscope',
    'Counting Monogram Stitches',
    'Counting Stitches in a Monogram with a Singularity Scanner',
    'Counting Stitches in a Monogram with a Tachyon Scanner',
    'Counting Threads in a Handkerchief via Holographic Projector',
    'Counting Threads in a Linen Handkerchief',
    'Counting Threads in a Silk Cravat via DNA-Scanning Loupe',
    'Counting Weave Dimensions in a 4D Silk Cravat',
    'Counting Weaves in a Silk Cravat with a Tachyon Microscope',
    'Counting Weaves in a Spun-Gold Handkerchief via Hologram',
    'Counting the Dots on a Silk Tie',
    'Counting the Stitches in a Monogram with a DNA Scanner',
    'Counting the Stitches in a Monogram with a Magnifier',
    'Counting the Stitches in a Monogram with a Singularity Scanner',
    'Counting the Stitches in a Monogram',
    'Counting the Threads in a Silk Cravat with a Quantum Microscope',
    'Counting the Threads in a Silk Cravat',
    'Counting the Weave Patterns in a Linen Handkerchief',
    'Dabbing Colognes with a Q-Tip',
    'Dabbing Cufflink with Quantum Scent Nanoparticles',
    'Dabbing Cufflink with Scented Dark Matter Nanoparticles',
    'Dabbing Cufflinks with Antimatter Scent Oil',
    'Dabbing Lapel with Essence of Collapsed Stars',
    'Dabbing Lapel with Essence of Distant Galaxies (Revised)',
    'Dabbing Lapel with Essence of Distant Supernovae',
    'Dabbing Wrist with Colognes',
    'Dabbing a Cufflink with Scented Dark Matter',
    'Dabbing a Cufflink with Scented Nanoparticles',
    'Dabbing a Cufflink with Scented Oil',
    'Dabbing a Lapel with Essence of Distant Galaxies',
    'Dabbing a Lapel with Rare Orchid Essence',
    'Dabbing a Lapel with Scented Water',
    'Dusting Lapel with a Silk Brush',
    'Dusting a Lapel with a Diamond-Encrusted Brush',
    'Dusting a Tailcoat with Anti-Gravity Feathers',
    'Dusting a Tailcoat with Photon-Enhanced Diamond Duster',
    'Dusting a Tailcoat with a Diamond-Encrusted Duster',
    'Dusting a Tailcoat with a Diamond-Tipped Brush',
    'Dusting a Tailcoat with a Feathers Duster',
    'Dusting a Tailcoat with a Photon-Enhanced Brush',
    'Dusting a Tailcoat with a Quantum Duster',
    'Dusting a Tailcoat with a Singularity-Enhanced Brush',
    'Dusting a Top Hat with Nebula-Infused Feather Duster',
    'Dusting a Top Hat with Nebula-Infused Microfibers',
    'Examining a Fob Chain with a Magnifier',
    'Filing a Monocle with Diamond-Encrusted Nanofiles',
    'Fluffing Cravat',
    'Fluffing a Linen Handkerchief with Dark Matter Puffs',
    'Fluffing a Linen Handkerchief with Quantum Fluff',
    'Fluffing a Linen Handkerchief with a Feather',
    'Fluffing a Silk Cravat with Anti-Gravity Puffs',
    'Fluffing a Silk Handkerchief with a Diamond-Tipped Brush',
    'Fluffing a Silk Handkerchief',
    'Fluffing a Silk Scarf with Singularity Fluff',
    'Fluffing a Silk Scarf with Warp-Field Micro-Airbrush',
    'Fluffing a Silk Scarf with a Feather Duster',
    'Fluffing a Silk Scarf with a Warp-Field Feathers Duster',
    'Fluffing a Silk Scarf',
    'Fluffing a Velvet Cufflink via Quantum Resonance',
    'Fluffing a Velvet Cufflink via Warp-Field Resonance',
    'Fluffing a Velvet Cufflink with Warp-Field Feathers',
    'Fluffing a Velvet Cufflink with a Micro-Airbrush',
    'Fluffing a Velvet Cufflink',
    'Folding Pocket Square Precisely',
    'Folding a Handkerchief into a 4D Hypercube',
    'Folding a Handkerchief into a Butterfly',
    'Folding a Handkerchief into a Fractal Peacock',
    'Folding a Handkerchief into a Multiverse Swan',
    'Folding a Handkerchief into a Peacock',
    'Folding a Handkerchief into a Quantum Butterfly',
    'Folding a Handkerchief into a Singularity Spiral',
    'Folding a Handkerchief into a Swan (Again)',
    'Folding a Handkerchief into a Swan',
    'Folding a Handkerchief into a Tesseract Swan',
    'Folding a Letter into a Crane',
    'Folding a Linen Cravat into a Perfect Origami Lotus',
    'Folding a Newspaper into a 5D Hypercube',
    'Folding a Newspaper into a Klein Bottle',
    'Folding a Newspaper into a Miniature Eiffel Tower',
    'Folding a Newspaper into a Perfect Cube',
    'Folding a Newspaper into a Time-Dilation Tower',
    'Folding a Newspaper with Precision',
    'Folding a Pocket Square into a Chroniton Rose',
    'Folding a Pocket Square into a Falcon',
    'Folding a Pocket Square into a Fractal Phoenix',
    'Folding a Pocket Square into a Fractal Rose',
    'Folding a Pocket Square into a Möbius Strip',
    'Folding a Pocket Square into a Phoenix',
    'Folding a Pocket Square into a Quantum Origami Falcon',
    'Folding a Pocket Square into a Rose',
    'Folding a Silk Scarf into an Origami Swan',
    'Infusing a Handkerchief with Nebula-Scented Nanoparticles',
    'Inspecting Lorgnette for Smudges',
    'Inspecting a Cane Tip with a Tachyon Microscope',
    'Inspecting a Cufflink with a Quantum Magnifier',
    'Inspecting a Silver Vinaigrette for Proper Aromatherapy Calibration',
    'Measuring Cravat Angle with a Holographic Protractor',
    'Measuring Cravat Angle with a Singularity Protractor',
    'Measuring Cravat Symmetry with a Digital Protractor',
    'Measuring Cravat Symmetry with a Graviton Ruler',
    'Measuring Cravat Symmetry with a Non-Euclidean Protractor',
    'Measuring Cuff Length with Calipers',
    'Measuring Cufflink Asymmetry with a Chroniton Ruler',
    'Measuring Cufflink Depth with Laser Calipers',
    'Measuring Cufflink Depth with a Quantum Ruler',
    'Measuring Cufflink Depth with a Subatomic Ruler',
    'Measuring Cufflink Depth with a Tachyon Ruler',
    'Measuring Cufflink Diameter with Calipers',
    'Measuring Cufflink Symmetry with a Laser Level',
    'Measuring Cufflink Symmetry with a Tachyon Ruler',
    'Measuring Cufflinks with Calipers',
    'Measuring Glove Fit with Calipers',
    'Measuring Glove Fit with Nanometer Precision',
    'Measuring Glove Fit with a Multidimensional Caliper',
    'Measuring Glove Fit with a Singularity Caliper',
    'Measuring Glove Gauntlet Tension with a Gravitational Sensor',
    'Measuring Glove Seam Tension with a Graviton Sensor',
    'Measuring Glove Seam Tension with a Tachyon Sensor',
    'Measuring Glove Seam Tension with a Tensiometer',
    'Measuring a Cravat with a Tailor\'s Tape',
    'Measuring the Perfect Cravat Angle',
    'Polishing Cufflinks with a Velvet Cloth',
    'Polishing Spectacles with a Monogrammed Cloth',
    'Polishing a Brass Knuckle Duster',
    'Polishing a Diamond-Encrusted Cane with Void Energy',
    'Polishing a Diamond-Encrusted Cigarette Case with Neutronium',
    'Polishing a Diamond-Encrusted Cufflink with Neutronium Polish',
    'Polishing a Diamond-Encrusted Shoe Horn with Exotic Matter',
    'Polishing a Diamond-Encrusted Shoe Horn',
    'Polishing a Diamond-Encrusted Snuff Box with Liquid Diamond',
    'Polishing a Diamond-Encrusted Snuff Box with Void Energy',
    'Polishing a Gold-Encrusted Pocket Watch',
    'Polishing a Gold-Plated Cane Tip with Liquid Platinum',
    'Polishing a Gold-Plated Cane Tip',
    'Polishing a Gold-Plated Cane with Liquid Platinum',
    'Polishing a Gold-Plated Cigarette Case with Neutronium',
    'Polishing a Gold-Plated Cufflink',
    'Polishing a Gold-Plated Monocle with Chroniton Polish',
    'Polishing a Gold-Plated Pocket Knife with a Microfiber Cloth',
    'Polishing a Gold-Plated Pocket Knife',
    'Polishing a Monocle Lens with Quantum-Enhanced Microfiber',
    'Polishing a Monogrammed Cufflink',
    'Polishing a Patent Leather Shoe',
    'Polishing a Platinum Cane Tip with Liquid Time',
    'Polishing a Platinum Cufflink',
    'Polishing a Platinum Monocle with Antimatter Polish',
    'Polishing a Platinum-Encrusted Cane with Exotic Matter',
    'Polishing a Platinum-Encrusted Monocle with Nano-Solution',
    'Polishing a Platinum-Plated Cane Tip with Exotic Matter',
    'Polishing a Platinum-Plated Cane with Neutronium Polish',
    'Polishing a Platinum-Plated Cane',
    'Polishing a Platinum-Plated Cigarette Case',
    'Polishing a Platinum-Plated Monocle with Antimatter Polish',
    'Polishing a Platinum-Plated Monocle',
    'Polishing a Ruby-Crusted Cane Tip with Liquid Time',
    'Polishing a Ruby-Encrusted Cane',
    'Polishing a Ruby-Encrusted Monocle with Void Polish',
    'Polishing a Ruby-Encrusted Pocket Square with Nebula Dust',
    'Polishing a Silver Cane Tip',
    'Polishing a Silver Cigarette Case',
    'Polishing a Silver Cigarette Holder',
    'Polishing a Silver Flask',
    'Polishing a Silver-Plated Snuff Box',
    'Polishing a Top Hat Band with Liquid Stardust',
    'Scenting a Letter with Lavender',
    'Sipping Absinthe through a Diamond-Encrusted Sugar Cube',
    'Sipping Absinthe through a Sugar Cube',
    'Sipping Ambrosia from a Celestial Chalice',
    'Sipping Ambrosia from a Celestial Nebula Goblet',
    'Sipping Ambrosia from a Chroniton-Infused Vessel',
    'Sipping Ambrosia from a Singularity Vessel',
    'Sipping Black Hole Brew from an Event Horizon Chalice',
    'Sipping Brandy from a Crystal Glass',
    'Sipping Brandy from a Gold-Plated Snifter',
    'Sipping Champagne from a Crystal Flute',
    'Sipping Earl Grey with Pinky Extended',
    'Sipping Elixir from a Chroniton-Infused Goblet',
    'Sipping Eternity from a Black Hole Decanter',
    'Sipping Eternity from a Timeless Chroniton Decanter',
    'Sipping Eternity from a Timeless Vessel',
    'Sipping Eternity through a Chroniton Filter',
    'Sipping Gilded Absinthe from a Singularity-Infused Glass',
    'Sipping Gin from a Crystal Goblet',
    'Sipping Liquid Starlight from a Cosmic Chalice',
    'Sipping Liquid Time from a Tachyon Chalice',
    'Sipping Port from a Crystal Decanter',
    'Sipping Rum from a Silver Goblet',
    'Sipping Sherry from a Crystal Decanter',
    'Sipping Starlight Brew from an Event Horizon Chalice',
    'Sipping Starlight from a Nebula Goblet',
    'Sipping Starlight through a Diamond-Encrusted Filter',
    'Sipping Tea through a Mustache Guard',
    'Sipping Whiskey from a Crystal Tumbler',
    'Straightening a Diamond Stickpin',
    'Straightening a Spats Buckle',
    'Stroking Silk Top Hat',
    'Stroking a Mutton Chop Whisker with a Diamond-Encrusted Comb',
    'Tapping Cane Rhythmically',
    'Tuning a Pocket Compass via Multiverse Alignment',
    'Tuning a Pocket Compass with a Chroniton Emitter',
    'Tuning a Pocket Compass with a Multiverse Dial',
    'Tuning a Pocket Watch via Black Hole Calibration'
    'Tuning a Pocket Watch via Multiverse Calibration Tool',
    'Tuning a Pocket Watch via Quantum Entanglement',
    'Tuning a Pocket Watch via Temporal Harmonic Key',
    'Tuning a Pocket Watch via Temporal Harmonic Resonator',
    'Tuning a Pocket Watch with a Chroniton Emitter',
    'Tuning a Pocket Watch with a Holographic Interface',
    'Tuning a Pocket Watch with a Loupe',
    'Tuning a Pocket Watch with a Microscope',
    'Tuning a Pocket Watch with a Multiverse Calibration Tool',
    'Tuning a Pocket Watch with a Multiverse Tuning Fork',
    'Tuning a Pocket Watch with a Quantum Calibrator',
    'Tuning a Pocket Watch with a Reality-Adjustment Dial',
    'Tuning a Pocket Watch with a Singularity Wrench',
    'Tuning a Pocket Watch with a Sonic Screwdriver',
    'Tuning a Pocket Watch with a Temporal Calibrator',
    'Tuning a Pocket Watch with a Tiny Screwdriver',
    'Tuning a Pocket Watch',
    'Twirling Monocle',
    'Twirling Mustache with Wax',
    'Twirling a Foil Epee',
    'Twirling a Pocket Watch Chain',
    'Twirling a Silk Handkerchief',
    'Twirling a Walking Stick',
    'Unfurling a Pocket Square',
)
