name: Nines Testing

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
      OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
      OPENAI_HOST: ${{ secrets.OPENAI_HOST }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DANDY_SETTINGS_MODULE: ${{ secrets.DANDY_SETTINGS_MODULE }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Dependencies
        run: |
          uv pip install --system -r development_requirements.txt      

      - name: 1 Nine Testing (90.0%)
        env:
          TESTING_NINES: 1
        run: |
          python -m unittest discover -v -f --top-level .

      - name: 2 Nine Testing (99.0%)
        if: ${{ success() }}
        env:
          TESTING_NINES: 2
        run: |
          python -m unittest discover -v -f --top-level .
